name: negern
description: Cross-platform VPN client (VLESS + AmneziaWG)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.2
  path: ^1.9.0
  dio: ^5.4.0
  mobile_scanner: ^5.2.3
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/builtin_profiles.json
